name: payday
description: "Payday - Modern expense tracking application."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.1.8+18

environment:
  sdk: ^3.9.0

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Firebase
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_analytics: ^11.3.3
  firebase_messaging: ^15.0.3 # Sürüm numarasını güncel tutun
  firebase_crashlytics: ^4.2.3
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1

  # Subscription & RevenueCat (✅ EKLENDİ)
  purchases_flutter: ^8.0.0

  # Ads
  google_mobile_ads: ^5.2.0

  # Environment Variables
  flutter_dotenv: ^5.1.0

  # UI & Design
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1

  # Utilities
  intl: ^0.20.0
  uuid: ^4.5.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1

  # Charts
  fl_chart: ^0.69.2

  # Functional Programming
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  currency_picker: ^2.0.21
  firebase_app_check: ^0.3.1+2
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  riverpod_generator: ^2.4.3
  freezed: ^2.5.7
  json_serializable: ^6.8.0

  # Native Splash
  flutter_native_splash: ^2.4.5

  # Launcher Icons
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/google_logo.svg
    - assets/icon.png
    - assets/splash.png
    - assets/inapp.png
    - .env

# Flutter native splash configuration
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  android: true
  ios: true

  # Dark mode'da da aynı beyaz splash kalsın
  color_dark: "#FFFFFF"
  image_dark: assets/splash.png

  android_12:
    color: "#FFFFFF"
    image: assets/splash.png
    color_dark: "#FFFFFF"
    image_dark: assets/splash.png
